// GETs
export const SET_CATEGORIES = "SET_CATEGORIES";
export const SET_CATEGORY_POSTS = "SET_CATEGORY_POSTS";
export const SET_COMMENT = "SET_COMMENT";
export const SET_POST = "SET_POST";
export const SET_POST_COMMENTS = "SET_POST_COMMENTS";
export const SET_ALL_POSTS = "SET_ALL_POSTS";

// POSTs
export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS";
export const ADD_POST_SUCCESS = "ADD_POST_SUCCESS";
export const VOTE_COMMENT_SUCCESS = "VOTE_COMMENT_SUCCESS";
export const VOTE_POST_SUCCESS = "VOTE_POST_SUCCESS";

// PUTs
export const EDIT_COMMENT_SUCCESS = "EDIT_COMMENT_SUCCESS";
export const EDIT_POST_SUCCESS = "EDIT_POST_SUCCESS";

// DELETEs
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";

// Other
export const SET_CATEGORY_SORT = "SET_CATEGORY_SORT";
export const SET_SORT = "SET_SORT";
